version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain dependencies for Python (Works recursively in application directories)
  - package-ecosystem: "pip"
    directory: "/applications"
    schedule:
      interval: "monthly"
    target-branch: "main"
    versioning-strategy: increase-if-necessary
