version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-action-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "applications"
      - "applications/django_rest"
      - "applications/django_graphql"
      - "applications/flask_rest"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/containers/docker/django_rest"
      - "/containers/docker/django_graphql"
    schedule:
      interval: "daily"
    target-branch: "main"
