version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-action-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Python (Works recursively in application directories)
  - package-ecosystem: "pip"
    directory: "/applications"
    schedule:
      interval: "weekly"
    target-branch: "main"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/containers/docker/django_rest"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/containers/docker/django_graphql"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/containers/podman/django_rest"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/containers/podman/django_graphql"
    schedule:
      interval: "weekly"
    target-branch: "main"
