line-length = 120
output-format = "github"
target-version = "py313"

[lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]
select = ["ALL"]

ignore = [
    "COM812",  # Ignore due to conflict with Ruff formatter
    "ISC001",  # Ignore due to conflict with Ruff formatter
    "PLR2004",
    "D104",
    "D100",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"applications/**test_*.py" = ["S101", "D102", "D103", "SLF001"]
"applications/django/manage.py" = ["TRY003", "EM101"]

[lint.pydocstyle]
convention = "google" # Use Google docstring convention.
