# Generated by Django 5.0.2 on 2024-02-13 11:59

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Represents a migration for the Hotels model."""

    initial: ClassVar[bool] = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
            ],
        )
    ]
