apiVersion: v1
kind: Service
metadata:
  name: django-graphql-service
spec:
  selector:
    app: django-graphql
  ports:
    - protocol: "TCP"
      port: 8000
      nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-graphql
spec:
  selector:
    matchLabels:
      app: django-graphql
  replicas: 1
  template:
    metadata:
      labels:
        app: django-graphql
    spec:
      automountServiceAccountToken: false
      containers:
        - name: django-graphql
          image: django_graphql:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 8000
