apiVersion: v1
kind: Service
metadata:
  name: django-rest-service
spec:
  selector:
    app: django-rest
  ports:
  - protocol: "TCP"
    port: 9001
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-rest
spec:
  selector:
    matchLabels:
      app: django-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: django-rest
    spec:
      containers:
      - name: django-rest
        image: django_rest:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
