---
name: Check for Required Pull Request Labels
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-for-required-labels:
    name: Check for Required Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check for Required Labels
        if: ${{ ! contains( github.event.pull_request.labels.*.name, 'dependencies')}}
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: updated-repository-visualisation
          add_comment: true
