---
name: Check for Required Pull Request Labels
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-for-required-labels:
    name: Check for Required Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Get changed files in the applications folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45.0.3
        with:
          files: applications/**
          files_ignore: |
            applications/requirements-dev.txt
            applications/*/requirements.txt
      - name: Check for Required Labels
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'dependencies') && steps.changed-files-specific.outputs.any_changed == 'true' }}
        uses: mheap/github-action-required-labels@v5.4.1
        with:
          mode: exactly
          count: 1
          labels: updated-repository-visualisation
          add_comment: true
