name: "Code Build"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [django_rest, django_graphql]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Image
        run: |
          cd applications/${{ matrix.folder }}
          make build
      - name: Run Image
        run: |
          cd applications/${{ matrix.folder }}
          make run
