name: "Code Test"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [django_rest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Development Requirements
        run: make development-install
      - name: Install Production Dependencies
        run: make install
        working-directory: ./applications/${{ matrix.folder }}
      - name: Unit Test
        run: make unit-test
        working-directory: ./applications/${{ matrix.folder }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.folder }}-coverage
          path: ./applications/${{ matrix.folder }}/.coverage
          retention-days: 1

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Development Requirements
        run: make development-install
      - name: test2
        run: ls
      - name: test3
        run: ls
        working-directory: ./django_rest-coverage
      - name: Combine Coverage Reports
        run: make coverage-combine-and-report
      - uses: sonarsource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.sources=applications,containers,deployment,requests
            -Dsonar.organization=jackplowman
            -Dsonar.projectKey=JackPlowman_python-playground
            -Dsonar.coverage.exclusions=tests/**,**/tests/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.12
            -Dsonar.exclusions=applications/**/tests/**
