name: "Code Build"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  container-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-application: [docker, podman]
        application: [django_rest, django_graphql]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Image
        run: |
          cd applications/${{ matrix.application }}
          make build-${{ matrix.build-application }}
      - name: Run Image
        run: |
          cd applications/${{ matrix.application }}
          make run-${{ matrix.build-application }}

  container-build-complete:
    runs-on: ubuntu-latest
    needs: container-build
    steps:
      - name: Build Image
        run: |
          echo "Build Complete"
