name: "Code Test"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [django_rest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Development Requirements
        run: make development-install
      - name: Install Production Dependencies
        run: make install
        working-directory: ./applications/${{ matrix.folder }}
      - name: Unit Test
        run: make unit-test
        working-directory: ./applications/${{ matrix.folder }}

  mutation-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [django_rest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Development Requirements
        run: make development-install
      - name: Install Production Dependencies
        run: make install
        working-directory: ./applications/${{ matrix.folder }}
      - name: Mutation Test
        run: make mutation-test
        working-directory: ./applications/${{ matrix.folder }}
