name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: EditorConfig Check
        uses: editorconfig-checker/action-editorconfig-checker@v2

  check-python-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Development Requirements
        run: make development-install

      - name: Python Format Check
        run: make python-format-check

      - name: Python Lint Check
        run: make python-lint-check

  check-markdown-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Markdown format
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          config: .github/workflows/config/.markdownlint.json

      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: .github/workflows/config/markdown-check-links.json
          base-branch: main
          check-modified-files-only: "no"

  prose-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: errata-ai/vale-action@v2.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}

  check-sql-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SQLFluff Check
        uses: yu-iskw/action-sqlfluff@v3
        with:
          working-directory: ${{ github.workspace }}/applications
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "2.3.5"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/applications/.sqlfluff"
          paths: "${{ github.workspace }}/applications"
          fail_on_error: "True"
          filter_mode: "nofilter"
