name: "Create diagram"

on:
  push:
    branches:
      - task/code_diagram

permissions: write-all

jobs:
  update-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
