name: "Create diagram"

on:
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  update-diagram:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'awaiting-code-diagram' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
