name: "Code Quality"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 1 * * 0"

permissions:
  contents: read

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: EditorConfig Check
        uses: zbeekman/EditorConfig-Action@v1.1.1
      - name: Python Format Check
        run: make python-format-check
      - name: Python Lint Check
        run: make python-lint-check
